name: Remove All Resources in AWS

on:
  push:
    branches:
      - kill

jobs:
  remove:
    name: remove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: serverless remove
        uses: serverless/github-action@v3
        with:
          args: remove
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


